[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.13.0"}
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.28.1"}
rojo = { github = "rojo-rbx/rojo", version = "=7.4.1"}
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "=0.3.0"}
selene = { github = "Kampfkarren/selene", version = "=0.26.1"}
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.20.0"}
